### ISSUE TITLE
Component idasen_desk_controller requires component esp32.

### ISSUE THREAD

**Issue by joshuajeschek** [j5lien/esphome-idasen-desk-controller#36]
Hey, this is my configuration:
```yaml
esphome:
  name: idasen
  platform: ESP32
  board: esp32dev

external_components:
  - source: github://j5lien/esphome-idasen-desk-controller@v3.0.0


esp32_ble_tracker:
ble_client:
  - mac_address: "00:00:00:00:00:00"
    id: idasen_desk

idasen_desk_controller:
  ble_client_id: idasen_desk
  only_up_down_command: false


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "..."

wifi:
  ssid: "..."
  password: "..."
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Idasen Fallback Hotspot"
    password: "..."

captive_portal:

```

When validating the configuration, I get the following error:
```bash
INFO Reading configuration /config/esphome/idasen.yaml...
Failed config

idasen_desk_controller: [source /config/esphome/idasen.yaml:16]
  
  Component idasen_desk_controller requires component esp32.
  ble_client_id: idasen_desk
  only_up_down_command: False
```

Do you have any idea why that might be? Any help is appreciated, thanks :D
